### ISSUE TITLE
Add media queries to all pages.

### ISSUE THREAD

**Issue by nok-ko** [ShakeGuard/2800-202210-BBY06#33]
## Media queries for:
- [x] Add a media query for the landing page.
- [x] Add a media query for the admin dashboard.
- [x] #34
- [x] Add a media query for the signup page.
- [x] Add a media query for the signup-success page.
- [x] Add a media query for the user profile page.

**Comment by ArtfulJW** [comment]
Finished Iteration 1 of 'Add Media Queries to all pages'.
