### ISSUE TITLE
Use one `<form>` element instead of many in `profile-component.html`

### ISSUE THREAD

**Issue by nok-ko** [ShakeGuard/2800-202210-BBY06#39]
Why do you have multiple `<form>` elements in this HTML file? Why not just use one `<form>` with many `<input>`s inside it?

Also, I think these inputs should have `<label>` elements.

From [MDN]():
> Associating a `<label>` with an [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element offers some major advantages:
> - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> - When a user clicks or touches/taps a label, the browser passes the focus to its associated input (the resulting event is also raised for the input). That increased hit area for focusing the input provides an advantage to anyone trying to activate it – including those using a touch-screen device.

_Originally posted by @nok-ko in https://github.com/ShakeGuard/2800-202210-BBY06/pull/26#discussion_r871969746_

**Comment by speakingoftime** [comment]
done! #61
